Tiles/Models/Data/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Tiles.Models.Data
{
    public class Post
    {
        public Post()
        {
        }

        public Post(string title, string content, DateTime publishDate)
        {
            Title = title;
            Content = content;
            PublishDate = publishDate;
        }

        

        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [Required(ErrorMessage = "Требуется заголовок")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Содержимое обязательно")]
        public string Content { get; set; }

        public string ShortDescription { get; set; }

        public DateTime PublishDate { get; set; }

        public List<string> Tags { get; set; }
    }
}

Tiles/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Tiles.Models;
using Tiles.Models.Data;

namespace Tiles.Controllers
{
    /// <summary>
    /// Cooming soon
    /// </summary>
    public class PostController : Controller
    {
        public PostsRepository PostsRepository { get; }

        public PostController(PostsRepository postsRepository) => 
            PostsRepository = postsRepository;


        public ActionResult Index() =>
            View(PostsRepository.AllPosts);


        public async Task<ActionResult> Details(string id)
        {
            var post = await PostsRepository.GetPost(id);

            if (post == null)
                return NotFound();

            return View(post);
        }


        [Authorize]
        [HttpGet]
        public ActionResult Create() =>
            View();


        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Create(Post post)
        {
            if (!ModelState.IsValid)
                return View();

            post.PublishDate = DateTime.Now;

            await PostsRepository.SavePost(post);

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            var post = await PostsRepository.GetPost(id);
            if (post == null)
                return NotFound();

            return View(post);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Edit(Post post)
        {
            if (!ModelState.IsValid)
                return View(post);

            await PostsRepository.UpdatePost(post);

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            var post = await PostsRepository.GetPost(id);
            if (post == null)
                return NotFound();

            await PostsRepository.DeletePost(post);

            return RedirectToAction(nameof(Index));
        }
    }
}

Tiles/Controllers/TileController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Tiles.Models;
using Tiles.Models.Data;

namespace Tiles.Controllers
{
    public class TileController : Controller
    {
        public TileRepository TilesRepository { get; }


        public TileController(TileRepository tilesRepository)
        {
            TilesRepository = tilesRepository;
        }


        public async Task<IActionResult> Index()
        {
            return View(await TilesRepository.AllTiles());
        }


        [Authorize]
        public IActionResult Create()
        {
            return View();
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(Tile tile)
        {
            if (!ModelState.IsValid)
                return View();

            await TilesRepository.SaveTile(tile);

            return Redirect("~/");
        }

        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
                return NotFound();

            await TilesRepository.DeleteTile(id);

            return Redirect("~/");
        }

        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
                return NotFound();

            var tile = await TilesRepository.FindTile(id);
            if(tile == null)
                return NotFound();

            return View(tile);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(Tile tile)
        {
            if (!ModelState.IsValid)
                return View(tile);

            await TilesRepository.EditTile(tile);

            return Redirect("~/");
        }
    }
}

Tiles/Views/Post/Create.cshtml
@model Tiles.Models.Data.Post

@{
    ViewBag.Title = "Create post";
    Layout = "_LayoutHome";
}

<div class="container bg-fill">
    <h1>Create post</h1>

    @Html.Partial("_PostForm", Model, Html.vd(new { action = "Create" }));
</div>

Tiles/Views/Post/Details.cshtml
@model Tiles.Models.Data.Post

@{
    ViewBag.Title = $"Post - {Model.Title}";
    Layout = "_LayoutHome";
}

<div class="container bg-fill">
    <h1>@Model.Title</h1>

    <markdown>@Html.Raw(Model.Content)</markdown>

    <hr />

    <a asp-controller="Tile" asp-action="Index">Home</a> | <a asp-controller="Post" asp-action="Index">All posts</a>

    @if (ViewContext.HttpContext.User.Identity.IsAuthenticated)
    {
        <text>|</text>
        <a asp-controller="Post" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        <text>|</text>
        <a asp-controller="Post" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
    }
</div>

Tiles/Views/Post/Edit.cshtml
@model Tiles.Models.Data.Post

@{
    ViewBag.Title = "Edit post";
    Layout = "_LayoutHome";
}

<div class="container bg-fill">
    <h1>Create post</h1>

    @Html.Partial("_PostForm", Model, Html.vd(new { action = "Edit" }));
</div>

Tiles/Views/Post/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@model IEnumerable<Tiles.Models.Data.Post>
@{
    ViewData["Title"] = "Posts";
    Layout = "_LayoutHome";
}

<div class="container">
    
    <h1 class="txt-color-white">Posts</h1>

    <div class="tiles">
        @foreach (var post in Model)
        {
            <a asp-controller="Post" asp-action="Details" asp-route-id="@post.Id">
                <div class="tile bg-fill">
                    <h4>@post.Title</h4>
                    <strong>@post.ShortDescription</strong>

                    <i>@post.PublishDate</i>
                </div>
            </a>
        }
    </div>

    @if (ViewContext.HttpContext.User.Identity.IsAuthenticated)
    {
        <a asp-controller="Post" asp-action="Create" class="txt-color-white">Create new post</a>
    }
</div>

Tiles/Views/Post/_PostForm.cshtml
@model Models.Data.Post

<form asp-controller="Post" asp-action="@ViewData["action"]" method="post">

    @if (Model != null)
    {
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    }

    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input type="text" class="form-control" asp-for="Title" placeholder="Enter tile title" value="@Model?.Title" />
    </div>

    <div class="form-group">
        <label asp-for="Content">Short description</label>
        <textarea class="form-control" asp-for="Content" placeholder="Enter tile description">@Model?.Content</textarea>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>